apiVersion: v1
kind: Pod
metadata:
  generateName: kp-runner-
spec:
  volumes:
  - name: runner-vol
    emptyDir: {}
  containers:
  - name: runner-container
    image: "docker-registry.default.svc:5000/kielipankki-github-runners/runner:v1.0.0"
    workingDir: /home/kprunner
    #    args: ["$(GITHUB_PAT)"]
    #    command: ["echo"]
    args: ["$(GITHUB_PAT)"]
    env:
      - name: GITHUB_PAT
        valueFrom:
          secretKeyRef:
            name: runner-secrets
            key: gh_runner_pat
            optional: false
  securityContext:
    runAsUser: 1031660001
