---

apiVersion: v1
kind: Pod
metadata:
  generateName: kp-course-runner-
spec:
  containers:
    - name: runner-container
      image: "image-registry.apps.2.rahti.csc.fi/kp-gh-actions-runners/course-runner:v1.1.1"
      workingDir: /home/kprunner
      args: ["$(GITHUB_PAT)"]
      env:
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: runner-secrets
              key: gh_runner_pat
              optional: false
        - name: RUNNER_REPO
          value: "csc-training/Kielipankki"
  securityContext:
    runAsUser: 1002480001
