---

apiVersion: v1
kind: Pod
metadata:
  generateName: kp-python-runner-
spec:
  containers:
    - name: runner-container
      image: "docker-registry.default.svc:5000/kielipankki-github-runners/python-runner:v1.1.0"
      workingDir: /home/kprunner
      args: ["$(GITHUB_PAT)"]
      env:
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: runner-secrets
              key: gh_runner_pat
              optional: false
        - name: RUNNER_REPO
          value: "CSCfi/kielipankki-nlf-harvester"
  securityContext:
    runAsUser: 1031660001
