---

apiVersion: v1
kind: Template
metadata:
  name: python-runner-template
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      generateName: kp-runner-${REPO_NAME}-
    spec:
      containers:
        - name: runner-container
          image: "docker-registry.default.svc:5000/kielipankki-github-runners/python-runner:v1.1.2"
          workingDir: /home/kprunner
          args: ["$(GITHUB_PAT)"]
          env:
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: runner-secrets
                  key: gh_runner_pat
                  optional: false
            - name: RUNNER_REPO
              value: ${REPO_OWNER}/${REPO_NAME}
      securityContext:
        runAsUser: 1031660001
parameters:
  - name: REPO_OWNER
    required: true
  - name: REPO_NAME
    required: true
