---

apiVersion: v1
kind: Template
metadata:
  name: python-runner-template
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      generateName: kp-runner-${REPO_NAME}-
    spec:
      containers:
        - name: runner-container
          image: "image-registry.apps.2.rahti.csc.fi/kp-gh-actions-runners/python-runner:v1.1.4"
          workingDir: /home/kprunner
          args: ["$(GITHUB_PAT)"]
          env:
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: runner-secrets
                  key: gh_runner_pat
                  optional: false
            - name: RUNNER_REPO
              value: ${REPO_OWNER}/${REPO_NAME}
          resources:
            limits:
              cpu: "250m"
              memory: "500Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
      securityContext:
        runAsUser: 1002480001
parameters:
  - name: REPO_OWNER
    required: true
  - name: REPO_NAME
    required: true
