---
name: Python static analysis pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  black:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install required Python packages
        run: python3 -m pip install black --user
      - name: Check formatting with Black
        run: python3 -m black --check .
